import { MigrantState } from "../../utils/types";

export default [
    {
        id: 0,
        name: "Ojeomokhai",
        nationality: "Nigerian",
        languages: ["English", "Yoruba"],
        shortBio: "Ojeomokhai is a 33 year old engineer seeking a better job market for his skill set.",
        bio: "",
        money: 60000,
        destination: "Sabha",
        state: MigrantState.Open,
    },        
    {
        id: 1,
        name: "Gloria",
        nationality: "Nigerien",
        languages: ["Hausa", "French"],
        shortBio: "A quiet, ambitious woman, Gloria is pursuing higher education in Europe to become a doctor.",
        bio: "",
        money: 80000,
        destination: "Tripoli",
        state: MigrantState.Open,
    },        
    {
        id: 2,
        name: "Calvin",
        nationality: "Cameroonian",
        languages: ["French", "Fang"],
        shortBio: "Calvin is looking to make it to Spain, where his brother is.",
        bio: "",
        money: 20000,
        destination: "Qatrun",
        state: MigrantState.Open,
    },        
    {
        id: 3,
        name: "Joseph",
        nationality: "Ghanian",
        languages: ["English", "Arabic", "Akan"],
        shortBio: "A painter expelled from Libya, Joseph seeks to return.",
        bio: "",
        money: 30000,
        destination: "Qatrun",
        state: MigrantState.Open,
    },        
    {
        id: 4,
        name: "Abdel",
        nationality: "Libyan",
        languages: ["Tedaga"],
        shortBio: "As the Toubou are persecuted in Libya, Abdel seeks to move in incognito.",
        bio: "",
        money: 60000,
        destination: "Sabha",
        state: MigrantState.Open,
    },        
    {
        id: 5,
        name: "Helen",
        nationality: "Nigerian",
        languages: ["English", "Hausa"],
        shortBio: "Weary after years of poverty and instability, Helen desires to leave Africa.",
        bio: "",
        money: 25000,
        destination: "Libya",
        state: MigrantState.Open,
    },        
    {
        id: 6,
        name: "Yusuf",
        nationality: "Ghanian",
        languages: ["English", "Akan"],
        shortBio: "Determined to make something of his youth, Yusuf left his small hometown to seek opportunity.",
        bio: "",
        money: 15000,
        destination: "Sabha",
        state: MigrantState.Open,
    },      
    {
        id: 7,
        name: "Moussa",
        nationality: "Malian",
        languages: ["English", "Hausa"],
        shortBio: "Moussa tried to return home, but her money was stolen, leaving her to go back to Sabha.",
        bio: "",
        money: 0,
        destination: "Sabha",
        state: MigrantState.Open,
    },        
    {
        id: 8,
        name: "Abdul",
        nationality: "Nigerian",
        languages: ["English", "Igbo", "Arabic"],
        shortBio: "Abdul dreams of becoming a printmaker, desiring to leave behind his job as a domestic.",
        bio: "",
        money: 20000,
        destination: "Tripoli",
        state: MigrantState.Open,
    },       
    {
        id: 9,
        name: "Paul",
        nationality: "Nigerian",
        languages: ["English", "Yoruba"],
        shortBio: "Paul is short of money to make the last leg of his trip to Europe.",
        bio: "",
        money: 1000,
        destination: "Tripoli",
        state: MigrantState.Open,
    },  
]